/// <reference types="next" />
/// <reference types="next/types/global" />

// This file ensures Next.js types are picked up by TypeScript in the frontend
// It is normally generated by Next, but we add it here so editors/CI see the types.
